
* ipython notebook
need to install jupyter instead of ipython notebook

pip3 install jupyter
maybe also need to run
pip3 install notebook (note sure)


And then before use the package inside emacs, need to start notebook using the following command:

ipython notebook (shouldn't use jupyter command here)
* shell
** read profile for shell
 eshell can't read profile. But shell is able to read profile
 http://stackoverflow.com/questions/16107820/how-to-make-emacs-s-shell-mode-source-my-profile-file 
You can create a file ~/.emacs_zsh (or .emacs_bash, emacs_sh, ...) that shell-mode will use on startup. My .emacs_bash is simply:
. ~/.profile
Just be sure to put a newline at the end of the sourcing line or it won't get executed.

* emacs started from shell can't access remote server
check whether there is proxy set. If we set proxy in shell profile, then every connection to the remote server will use that proxy. one workaround is to set the no_proxy value
#+BEGIN_SRC bash
export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com,.github.com"
#+END_SRC

* shortcut
** switch between alternative buffer
SPACE + TAB
** helm follow mode
http://emacs.stackexchange.com/questions/27783/helm-find-projectile-file-how-to-view-the-file-content-when-choose-the-file
Add C-z or whatever key you want for helm-execute-persistent-action to helm-map first (define-key helm-map (kbd "C-z") 'helm-execute-persistent-action)
#+BEGIN_SRC elisp
(define-key helm-map (kbd "C-z") 'helm-execute-persistent-action)
#+END_SRC
** magit
** show the commit content without change window focus
http://emacs.stackexchange.com/questions/27798/how-to-view-each-commit-in-magit-easily
magit-diff-show-or-scroll-up

in spacemacs it mapps to Shift + Space

** all possible shortcut
use Meta + X 
